# Generated by Django 4.1.3 on 2022-12-29 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('TeamNumber', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=30)),
                ('Points', models.IntegerField()),
                ('Credits', models.IntegerField()),
            ],
        ),
    ]
